Add 2023 version: 1.4.0, build number: 473
and switch to current JRE to avoid
	java.lang.UnsupportedClassVersionError: com/ifactory/launch/IFApplicationLauncher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0